version: '3.8'

services:
  order_service:
    build:
      context: ./order_service 
    container_name: order_service
    ports:
      - "8000:8000"
    volumes:
      - ./order_service:/var/www
    networks:
      - app_network

  catalog_service:
    build:
      context: ./catalog_service  
    container_name: catalog_service
    ports:
      - "8001:8001"
    volumes:
      - ./catalog_service:/var/www
    networks:
      - app_network

  client_service:
    build:
      context: ./client_service  
    container_name: client_service
    ports:
      - "8002:8002"
    volumes:
      - ./client_service:/var/www
    networks:
      - app_network      

networks:
  app_network:
    driver: bridge

volumes:
  shared_data:  
    driver: local