version: '3.8'

services:
  client_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./app/client:/var/www/app
      - ./public:/var/www/public
      - ./bootstrap:/var/www/bootstrap
      - ./vendor:/var/www/vendor
      - ./app/Exceptions:/var/www/app/Exceptions
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - client_db:/var/www/database/db
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/db/client.sqlite
      APP_DEBUG: "true"

  catalog_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./app/catalog:/var/www/app
      - ./public:/var/www/public
      - ./bootstrap:/var/www/bootstrap
      - ./vendor:/var/www/vendor
      - ./app/Exceptions:/var/www/app/Exceptions
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - catalog_db:/var/www/database/db
    ports:
      - "9001:9000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/db/catalog.sqlite
      APP_DEBUG: "true"

  catalog2_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./app/catalog2:/var/www/app
      - ./public:/var/www/public
      - ./bootstrap:/var/www/bootstrap
      - ./vendor:/var/www/vendor
      - ./app/Exceptions:/var/www/app/Exceptions
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - catalog2_db:/var/www/database/db
    ports:
      - "9002:9000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/db/catalog2.sqlite
      APP_DEBUG: "true"

  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./app/order:/var/www/app
      - ./public:/var/www/public
      - ./bootstrap:/var/www/bootstrap
      - ./vendor:/var/www/vendor
      - ./app/Exceptions:/var/www/app/Exceptions
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - order_db:/var/www/database/db
    ports:
      - "9003:9000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/db/order.sqlite
      APP_DEBUG: "true"

  order2_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./app/order2:/var/www/app
      - ./public:/var/www/public
      - ./bootstrap:/var/www/bootstrap
      - ./vendor:/var/www/vendor
      - ./app/Exceptions:/var/www/app/Exceptions
      - ./routes:/var/www/routes
      - ./database:/var/www/database
      - order2_db:/var/www/database/db
    ports:
      - "9004:9000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/db/order2.sqlite
      APP_DEBUG: "true"

volumes:
  client_db:
  catalog_db:
  catalog2_db:
  order_db:
  order2_db:
