

services:
  client_service:
    build:
      context: ./client
      dockerfile: ../Dockerfile
    volumes:
      - ./client:/var/www
      - client_db:/var/www/database/db
    ports:
      - "9000:9000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/db/client.sqlite

  catalog_service:
    build:
      context: ./catalog
      dockerfile: ../Dockerfile
    volumes:
      - ./catalog:/var/www
      - catalog_db:/var/www/database/db
    ports:
      - "9001:9000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/db/catalog.sqlite

  catalog2_service:
    build:
      context: ./catalog2
      dockerfile: ../Dockerfile
    volumes:
      - ./catalog2:/var/www
      - catalog2_db:/var/www/database/db
    ports:
      - "9002:9000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/db/catalog2.sqlite

  order_service:
    build:
      context: ./order
      dockerfile: ../Dockerfile
    volumes:
      - ./order:/var/www
      - order_db:/var/www/database/db
    ports:
      - "9003:9000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/db/order.sqlite

  order2_service:
    build:
      context: ./order2
      dockerfile: ../Dockerfile
    volumes:
      - ./order2:/var/www
      - order2_db:/var/www/database/db
    ports:
      - "9004:9000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/db/order2.sqlite

volumes:
  client_db:
  catalog_db:
  catalog2_db:
  order_db:
  order2_db:
